[2024-07-31T19:31:30.009+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T19:31:30.018+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-app.transform_weather_data manual__2024-07-31T19:26:43.324703+00:00 [queued]>
[2024-07-31T19:31:30.024+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-app.transform_weather_data manual__2024-07-31T19:26:43.324703+00:00 [queued]>
[2024-07-31T19:31:30.025+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-31T19:31:30.041+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_weather_data> on 2024-07-31 19:26:43.324703+00:00
[2024-07-31T19:31:30.046+0000] {standard_task_runner.py:64} INFO - Started process 6410 to run task
[2024-07-31T19:31:30.049+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather-app', 'transform_weather_data', 'manual__2024-07-31T19:26:43.324703+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmp3vofuznu']
[2024-07-31T19:31:30.050+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask transform_weather_data
[2024-07-31T19:31:30.085+0000] {task_command.py:426} INFO - Running <TaskInstance: weather-app.transform_weather_data manual__2024-07-31T19:26:43.324703+00:00 [running]> on host ip-172-31-15-224.ap-southeast-2.compute.internal
[2024-07-31T19:31:30.150+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather-app' AIRFLOW_CTX_TASK_ID='transform_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-31T19:26:43.324703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-31T19:26:43.324703+00:00'
[2024-07-31T19:31:30.151+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T19:31:30.160+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T19:31:30.160+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 51, in transform_data
    df_data.to_csv(f"{df_string}.csv",index-False)
                      ^^^^^^^^^
NameError: name 'df_string' is not defined. Did you mean: 'dt_string'?
[2024-07-31T19:31:30.166+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-app, task_id=transform_weather_data, run_id=manual__2024-07-31T19:26:43.324703+00:00, execution_date=20240731T192643, start_date=20240731T193130, end_date=20240731T193130
[2024-07-31T19:31:30.177+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task transform_weather_data (name 'df_string' is not defined; 6410)
[2024-07-31T19:31:30.221+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-31T19:31:30.232+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-31T19:31:30.233+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
